name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: test-1111
          aws-secret-access-key: test-2222
          aws-region: us-east-2
      - name: Run tests
        run: |
          sudo apt-get install -y awscli
          cargo test --verbose
          RUNNER_TRACKING_ID="" && (nohup cargo run --verbose -- --working-folder /tmp/&)
          sleep 10
          aws --endpoint-url http://localhost:9090 s3 mb s3://sardo
          aws --endpoint-url http://localhost:9090 s3 ls
        
